export ALIASES=$HOME/Dotfiles/aliases

# load customized aliases
source $ALIASES/system
source $ALIASES/basic
source $ALIASES/tools
source $ALIASES/dev

# autoload scripts
export SCRIPTS=$HOME/Dotfiles/scripts
export PATH="$SCRIPTS:$PATH"

if [[ "Darwin" != $(uname -s) ]]; then
  # enter xwindow after console login
  if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
  fi

fi

