#!/bin/sh
export SCRIPTS=$HOME/Dotfiles/scripts

# hdpi scales
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_ENABLE_HIGHDPI_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1.4
export GDK_SCALE=0.8
export GDK_DPI_SCALE=0.7

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# xft resources
xrdb -merge ~/.Xresources

# render shell status bar
sh $SCRIPTS/status-bar &

# adjust monitors and wallpapers
monitor
wallpaper

# dual monitors recover after suspend
# https://bugs.launchpad.net/ubuntu/+source/kscreen/+bug/1573345
# https://unix.stackexchange.com/questions/510244/hdmi-monitors-not-correctly-detected-after-suspend-if-laptop-lid-closed
#xset -dpms

# enable screensaver if idle for 10 minutes
xset s 600
xss-lock --ignore-sleep lock &

# alpha and shadow effect
/usr/local/bin/picom &
# xcompmgr -c -C -t-5 -l-5 -r3.3 -o.33 > /dev/null &

# ibus input
# GTK_IM_MODULE=ibus
# QT_IM_MODULE=ibus
# XMODIFIERS=@im=ibus
# export XMODIFIERS GTK_IM_MODULE QT_IM_MODULE
# ibus-daemon -drx

GTK_IM_MODULE=fcitx5
QT_IM_MODULE=fcitx5
XMODIFIERS="@im=fcitx5"
export XMODIFIERS GTK_IM_MODULE QT_IM_MODULE
fcitx5 -d

# propogate DISPLAY 
sh /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# start other programs
rescuetime > /dev/null &

# set keyboard 
remap

# universal key bindings 
xbindkeys

# adjust color temperature
nohup bash -c "sleep 15; systemctl --user start redshift" &

# game on
start-dwm
