#!/bin/sh
export SCRIPTS=$HOME/Dotfiles/scripts

# hdpi scales
#export QT_QPA_PLATFORMTHEME=gtk2
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_ENABLE_HIGHDPI_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1.4
export GDK_SCALE=0.8
export GDK_DPI_SCALE=0.7

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# xft resources
xrdb -merge ~/.Xresources

# render shell status bar
sh $SCRIPTS/status-bar &

# adjust monitors and wallpapers
monitor
wallpaper

# dual monitors recover after suspend
# https://bugs.launchpad.net/ubuntu/+source/kscreen/+bug/1573345
# https://unix.stackexchange.com/questions/510244/hdmi-monitors-not-correctly-detected-after-suspend-if-laptop-lid-closed
#xset -dpms

xset s 600
xss-lock --ignore-sleep lock &

# alpha and shadow effect
#compton -cCGf &

# ibus input
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
export XMODIFIERS GTK_IM_MODULE QT_IM_MODULE
ibus-daemon -drx

# propogate DISPLAY 
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# start other programs
rescuetime > /dev/null &

# set keyboard 
remap

# universal key bindings 
xbindkeys

# game on
#exec /usr/local/bin/dwm
start-dwm
