#!/bin/sh

RECORD_FOLDER="$HOME/Documents/Records"
CASTPID_FILE="/tmp/castpid"
webcam() {
  pkill -f '/dev/video' && mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video2 > /dev/null 2>&1 &
}

capture() {
  /usr/bin/screencast -S -W -I /dev/video2 -P bottomright "$RECORD_FOLDER/screencast-$(date '+%Y%m%d-%H%M-%S').mp4"
}

capture_full() { 
	ffmpeg -y \
	-f x11grab \
	-framerate 60 \
	-s "3840x2160" \
	-i "$DISPLAY" \
	-f alsa -i default \
	-r 30 \
 	-c:v h264 -crf 0 -preset ultrafast -c:a aac \
	"$RECORD_FOLDER/screencast-$(date '+%Y%m%d-%H%M-%S').mp4" > /dev/null 2>&1 &
	echo $! > $CASTPID_FILE
  notify-send "Screencast is starting..."
}

record() {
  ffmpeg -f v4l2 \
  -video_size 1280x800 \
  -i /dev/video2 \
  -f alsa \
  -i default \
  -c:v libx264 \
  -preset ultrafast \
  -c:a aac \
  $RECORD_FOLDER/cam_$(date '+%Y%m%d-%H%M-%S').mp4 > /dev/null 2>&1 &
  echo $! > $CASTPID_FILE
  notify-send "Camcast is starting..."
}

killcasting() {
  PID=$(cat $CASTPID_FILE)
  kill -15 $PID
  rm $CASTPID_FILE
  notify-send "Casting is stopped."
}

openrecord() {
  cd $RECORD_FOLDER && cvlc $(ls -t $1* | head -n1) 
}

stream_dslr() {
  gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -r 25 -s 1080x720 -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video20
}

case "$1" in
  show) webcam;;
	cam) record;;
	screen) capture;;
	stop) killcasting;;
  open) openrecord $2;;
  stream) stream_dslr;;
	*) webcam;;
esac
