#!/bin/sh

DMENU="fuzzel -d"
CHOICE="$1"

while true; do
    if [ -z "$CHOICE" ]; then
        CHOICE=$(cat /usr/share/dict/words | $DMENU)
    elif [ $CHOICE = "/q" ]; then
        exit 0
    else
        RESULT=$(sdcv -n -e -0 -j "$CHOICE" | jq -r ".[0].definition")
        if [ -n "$RESULT" ]; then
            CHOICE=$(echo "$RESULT" | $DMENU)
        fi
    fi

done
