#!/bin/sh

config="$HOME/.config/hypr/hyprland.conf"

right=$(hyprctl monitors -j | jq -r '.[0].name')
left=$(hyprctl monitors -j | jq -r '.[1].name')

sed -i "s/\$monitor_left\s=.*$/\$monitor_left = $left/g" $config 

sed -i "s/\$monitor_right\s=.*$/\$monitor_right = $right/g" $config

echo "Monitors set to $left and $right"
