#!/bin/sh

classic() {
  PLACE=$(echo -e "Clipboard\n Dropbox" | dmenu -p "Screenshot saves to ->" -b -fn 'Terminus:size=20')
  if [ $PLACE == "Clipboard" ]; then
    grim -g "$(slurp)" - | wl-copy -t image/png
  elif [ $PLACE == "Dropbox" ]; then
    FILE=$HOME/Dropbox/Pics/Screenshots/$(date +%s).png
    grim -g "$(slurp)" $FILE
    echo "$FILE" | wl-copy
  fi
}

#classic

QT_SCALE_FACTOR=1 && flameshot gui #-c -p $HOME/Dropbox/Pics/Screenshots/
