awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14
sans: &sans JetBrains Mono:pixelsize=17:style=semibold, Hiragino Sans GB W3:pixelsize=16

bar:
  monitor: DP-4
  layer: bottom
  height: 32
  location: top
  spacing: 15
  margin: 5

  font: xos4 Terminess Powerline:pixelsize=18:style=bold:antialias=true:autohint:true, Cantarell:pixelsize=16, Hiragino Sans GB W3:pixelsize=16, FontAwesome:pixelsize=16
  background: 1e1e2e99
  foreground: f8f8f2ff

  left:
    - i3:
        anchors:
          - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: "{name}"}
          - focused: &focused {deco: {underline: {size: 2, color: ffffffff}}}

        content:
          "": 
            map:
              conditions:
                state == focused: {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: *default}}
                state == urgent: {string: {<<: *default}}

  center:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                # - string: {text: "{app-id}", foreground: ffa0a0ff}
                - string: {text: "{title}"}

  right:

    - script:
        poll-interval: 5000
        path: /home/mike/Dotfiles/scripts/bars
        args: ["music"]
        content:
          map:
            conditions:
              status == "Playing":
                string: 
                  text: "\uf04b {artist} - {title}"
                  on-click: sh -c "playerctl pause"
              status == "Paused":
                string: 
                  text: "\uf04c {artist} - {title}"
                  on-click: sh -c "playerctl play"

    - script:
        poll-interval: 10000
        path: /home/mike/Dotfiles/scripts/bars
        args: ["timew"]
        content:
          map:
            conditions:
              running:
                string: 
                  text: "\uf017 {interval} {tag}" 
                  on-click: sh -c "timew stop"

    - script:
        poll-interval: 10000
        path: /home/mike/Dotfiles/scripts/bars
        args: ["tasks"]
        content: { string: { text: "\uf024 {count}" }}

    - script:
        poll-interval: 10000
        path: /home/mike/Dotfiles/scripts/bars
        args: ["mail"]
        content: { string: { text: "\uf0e0 {unreads}" }}

    - mem:
       poll-interval: 2500
       content:
         string: {text: "{used:gb}GB"}

    - cpu:
       poll-interval: 2500
       content:
         map:
           conditions:
             id < 0:
               - string: {text: "\uf0d8"}
               - string: {text: "{cpu}%"}
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          string: {text: " {capacity}%"}
    - pulse:
        content: 
          string: 
            text: "\uf027 {sink_percent}% ({sink_port})"
            on-click: pavucontrol

    - network:
        name: wlp2s0
        poll-interval: 30000
        content:
          map:
            default: 
              - string: {text: , font: *awesome}
              - string: {text: " {ssid}"}
            conditions:
              state == down: {string: {text: , font: *awesome}}

    - script:
        poll-interval: 1000
        path: /home/mike/Dotfiles/scripts/bars
        args: ["cst"]
        content:  
          string: 
            text: "{clock}" 
            on-click: gnome-clocks

    - clock:
        time-format: "%H:%M"
        date-format: "%b %d %a"
        content:
          - string: {text: "{date}", right-margin: 5}
          - string: 
              text: "{time}"
              on-click: gnome-calendar

